### ISSUE TITLE
Fatal error since last update

### ISSUE THREAD

**Issue by maximejobin** [bluehost/bluehost-wordpress-plugin#203]
Fatal error since last update.

I'm with SatelliteWP, a maintenance service for WordPress websites owners. We don't directly use your services but some potential clients contacted us. I do not have more information about what happened. I see many people on Twitter complaining too so I'm opening this ticket in hope that you can help your clients ASAP. :-)

```
Warning: Undefined variable $bh_data in /home2/xxxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/bluehost/bluehost-wp-customer-data/includes/Customer.php on line 42

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in /home2/xxxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/bluehost/bluehost-wp-customer-data/includes/Customer.php:45 Stack trace: #0 /home2/xxxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/bluehost/bluehost-wp-customer-data/includes/Customer.php(45): array_key_exists('plan_subtype', false) #1 /home2/xxxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-onboarding/includes/Data/Data.php(116): Bluehost\WP\Data\Customer::collect() #2 /home2/xxxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/newfold-labs/wp-module-onboarding/includes/ModuleController.php(31): NewfoldLabs\WP\Module\Onboarding\Data\Data::customer_data() #3 /home2/xxxx/public_html/wp-includes/class-wp-hook.php(305): NewfoldLabs\WP\Module\Onboarding\ModuleController::module_switcher() #4 /home2/xxxx/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #5 /home2/xxxx/public_html/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #6 /home2/xxxx/public_html/wp-settings.php(576): do_action('after_setup_the...') #7 /home2/xxxx/public_html/wp-config.php(101): require_once('/home2/xxxx...') #8 /home2/xxxx/public_html/wp-load.php(50): require_once('/home2/xxxx...') #9 /home2/xxxx/public_html/wp-blog-header.php(13): require_once('/home2/xxxx...') #10 /home2/xxxx/public_html/index.php(17): require('/home2/xxxx...') #11 {main} thrown in /home2/xxxx/public_html/wp-content/plugins/bluehost-wordpress-plugin/vendor/bluehost/bluehost-wp-customer-data/includes/Customer.php on line 45
```

**Comment by maximejobin** [comment]
It seems like this commit was not included in your latest update:

https://github.com/bluehost/bluehost-wp-customer-data/commit/b6c63a0979a1f088e5516901708943f7769b99dd

There are so many commits in the other project in the last 24 hours. How could that be pushed to production so fast?
